# Generated by Django 5.1.6 on 2025-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_account_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='gyananjanrath123@gmail.com', max_length=254),
        ),
    ]
