# Generated by Django 5.1.6 on 2025-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_account_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
